spring:
  datasource:
    url: jdbc:mysql://integrated-mysql:3306/integrated_praise?useSSL=false&characterEncoding=utf8
  cloud:
    stream:
      function:
        definition: praise;
      bindings:
        # https://docs.spring.io/spring-cloud-stream/docs/3.2.6/reference/html/spring-cloud-stream.html#_functional_binding_names
        # input - <functionName> + -in- + <index>
        # output - <functionName> + -out- + <index>
        praise-in-0:
          destination: PRAISE-TOPIC-01
          content-type: application/json
          group: consumer-group-test
      rocketmq:
        binder:
          name-server: rocketmq:9876
        bindings:
          praise-in-0:
            consumer:
              pullInterval: 4000
              pullBatchSize: 4